# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# SPDX-License-Identifier: BSD-3-Clause

"""Auto-generated pick_place teleop env_cfg.

This file is generated by my_docs/env_cfg_skills/orchestrator.py.
It subclasses an existing repository env_cfg template and only overrides
task-specific object/table/target parameters derived from the validated spec.
"""

from isaaclab.utils.assets import ISAAC_NUCLEUS_DIR, ISAACLAB_NUCLEUS_DIR
from isaaclab_physx.sim.schemas import PhysxRigidBodyPropertiesCfg
from isaaclab.sim.schemas.schemas_cfg import MassPropertiesCfg

from .pickplace_unitree_g1_inspire_hand_env_cfg import PickPlaceG1InspireFTPEnvCfg
from .pickplace_seres_r11_env_cfg import SingleRigidBodyUsdFileCfg


class AutoPickPlaceUnitreeG1BottledWaterC01TeleopEnvCfg(PickPlaceG1InspireFTPEnvCfg):
    """Auto task for unitree_g1_inspire_ftp + bottled_water_c01."""

    def __post_init__(self):
        super().__post_init__()

        # Deterministic overrides from PickPlaceVRSpec presets.
        self.scene.object.spawn = SingleRigidBodyUsdFileCfg(
            usd_path=f"{ISAAC_NUCLEUS_DIR}/SimReady/Residential/Kitchen/Food/Beverages/Bottled_Water_C01/sm_food_beverage_bottledWater_c01_01.usd",
            scale=(1.0, 1.0, 1.0),
            rigid_props=PhysxRigidBodyPropertiesCfg(),
            mass_props=MassPropertiesCfg(mass=0.05),
        )
        self.scene.object.init_state.pos = (0.0, 0.45, 0.9996)
        self.scene.object.init_state.rot = (0.0, 0.0, 0.0, 1.0)
        self.scene.packing_table.init_state.pos = (0.0, 0.55, 0.0)
        self.scene.packing_table.init_state.rot = (0.0, 0.0, 0.0, 1.0)
        self.target_pose = {'pos': [0.25, 0.45, 0.9996], 'quat_xyzw': [0.0, 0.0, 0.0, 1.0]}
